// <auto-generated />
using Achilles.Acme.Content.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Achilles.Acme.Content.Data.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20171102144521_CreateContentSchema")]
    partial class CreateContentSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Achilles.Acme.Content.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CommentId");

                    b.Property<int?>("PostId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("cms_Comments");
                });

            modelBuilder.Entity("Achilles.Acme.Content.Data.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentTypeUId")
                        .IsRequired();

                    b.HasKey("PostId");

                    b.ToTable("cms_Posts");
                });

            modelBuilder.Entity("Achilles.Acme.Content.Data.Models.PostTags", b =>
                {
                    b.Property<int>("PostId");

                    b.Property<int>("TagId");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("cms_PostTags");
                });

            modelBuilder.Entity("Achilles.Acme.Content.Data.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("ParentTagId");

                    b.HasKey("TagId");

                    b.ToTable("cms_Tags");
                });

            modelBuilder.Entity("Achilles.Acme.Content.Data.Models.Comment", b =>
                {
                    b.HasOne("Achilles.Acme.Content.Data.Models.Comment")
                        .WithMany("Responses")
                        .HasForeignKey("CommentId");

                    b.HasOne("Achilles.Acme.Content.Data.Models.Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("Achilles.Acme.Content.Data.Models.PostTags", b =>
                {
                    b.HasOne("Achilles.Acme.Content.Data.Models.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Achilles.Acme.Content.Data.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
